FROM mcr.microsoft.com/mssql-tools

RUN apt-get update

RUN apt-get install -y -f wget 

COPY ./scripts/ /tmp/

COPY ./ini-database.sh /tmp/ini-database.sh

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz